import type { Algorithms } from '@/lib/algorithms'
export function AlgorithmOptions({ value, onChange }: { value: Algorithms; onChange: (next: Algorithms) => void }) {
  const set = (key: keyof Algorithms, next: string | boolean | number) => onChange({ ...value, [key]: next })
  return <section className="algorithm-options"><h3>Solver settings</h3><p>LP choices also apply to MILP node relaxations. QP uses its own method.</p><div className="form-grid">
    <label>LP method<select value={value.algorithm} onChange={e => set('algorithm', e.target.value)}><option value="auto">Automatic (interior point + fallback)</option><option value="simplex">Revised simplex</option><option value="ipm">Primal-dual interior point</option></select></label>
    <label>QP method<select value={value.qpAlgorithm} onChange={e => set('qpAlgorithm', e.target.value)}><option value="auto">Automatic</option><option value="ipm">Primal-dual interior point</option><option value="frank_wolfe">Frank–Wolfe</option></select></label>
    <label>MILP method<select value={value.milpMethod} onChange={e => set('milpMethod', e.target.value)}><option value="branch_and_cut">Branch-and-cut</option><option value="branch_and_bound">Branch-and-bound (cuts off)</option></select></label>
    <label>Branching rule<select value={value.branchRule} onChange={e => set('branchRule', e.target.value)}><option value="strong">Strong branching</option><option value="pseudocost">Pseudocost</option><option value="most_fractional">Most fractional</option></select></label>
  </div><details className="advanced-options"><summary>Search limits & presolve</summary><div className="form-grid"><label>Maximum MILP nodes<input type="number" min={1} max={1000000} required value={value.maxNodes} onChange={e => set('maxNodes', Number(e.target.value))} /></label><label>Presolve<select value={String(value.presolve)} onChange={e => set('presolve', e.target.value === 'true')}><option value="true">Enabled</option><option value="false">Disabled (comparison run)</option></select></label></div><label className="checkbox-label"><input type="checkbox" checked={value.parallelBranching} onChange={e => set('parallelBranching', e.target.checked)} />Parallel strong branching (Windows workers)</label></details></section>
}
